#!/usr/bin/env python3
"""Check actual supervisor speech candidates; semantic acceptance remains reviewed.

Input JSONL: case_id, model, prompt_version, spoken_text, evidence_ids.
This tool never substitutes fixture prose for a model output or calls a provider.
"""
import argparse
import json
from pathlib import Path
import re


PATTERNS = {
    "list formatting": r"(?m)^\s*(?:[-*•]\s|\d+[.)]\s|#{1,6}\s)",
    "code formatting": r"`|(?m:^\s*(?:fn |def |function |const |let |import |SELECT ))",
    "URL": r"(?:https?://|www\.)\S+",
    "file path": r"(?:/(?:home|mnt|tmp|src|crates|packages)/|\b\w+/(?:\w+/)*\w+\.\w+)",
    "opaque identifier": r"\b(?:[a-f0-9]{12,}|[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12})\b",
    "structured metadata": r"(?m)^\s*[A-Za-z /]+::|[\[{]\s*\"[^\"]+\"\s*:",
}


def structural_issues(text: str) -> list[str]:
    if not text.strip():
        return ["empty spoken text"]
    issues = [name for name, pattern in PATTERNS.items() if re.search(pattern, text)]
    if "\n|" in text or re.match(r"\s*\|.+\|", text):
        issues.append("table formatting")
    return issues


def evaluate(cases: list[dict], outputs: list[dict]) -> dict:
    expected = {case["id"]: case for case in cases}
    seen = set()
    results = []
    for output in outputs:
        case_id = output.get("case_id")
        errors = []
        if case_id not in expected:
            errors.append("unknown case")
        if case_id in seen:
            errors.append("duplicate case")
        seen.add(case_id)
        if not output.get("model") or not output.get("prompt_version"):
            errors.append("missing model/prompt provenance")
        spoken = output.get("spoken_text")
        if not isinstance(spoken, str):
            errors.append("missing spoken text")
        else:
            errors.extend(structural_issues(spoken))
        if case_id in expected:
            required = {report["id"] for report in expected[case_id]["reports"]}
            references = output.get("evidence_ids", [])
            if not isinstance(references, list) or not all(isinstance(item,str) for item in references):
                errors.append("invalid evidence references")
            elif set(references) != required:
                errors.append("missing or invented source evidence reference")
        results.append({"case_id":case_id,"structural_issues":errors,"semantic_review":"required"})
    missing = sorted(set(expected) - seen)
    return {"structural_pass":not missing and all(not row["structural_issues"] for row in results),
            "missing_cases":missing,"cases":results,"acceptance":"unverified: real outputs require semantic review"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("outputs",type=Path,help="JSONL generated by the configured supervisor model")
    parser.add_argument("--cases",type=Path,default=Path(__file__).with_name("speech_cases.json"))
    args = parser.parse_args()
    cases = json.loads(args.cases.read_text())["cases"]
    outputs = [json.loads(line) for line in args.outputs.read_text().splitlines() if line.strip()]
    report = evaluate(cases,outputs)
    print(json.dumps(report,indent=2))
    return 0 if report["structural_pass"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
